// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Course struct {
	Nombre      string  `json:"nombre"`
	Descripcion *string `json:"descripcion"`
	Temas       *string `json:"temas"`
}

type Record struct {
	Student    string  `json:"student"`
	Course     string  `json:"course"`
	Startdate  *string `json:"startdate"`
	Finishdate *string `json:"finishdate"`
}

type Student struct {
	Nombre          *string `json:"nombre"`
	Dni             string  `json:"dni"`
	Direccion       *string `json:"direccion"`
	FechaNacimiento *string `json:"fecha_nacimiento"`
}
